# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ede81d5eadc47e5e8f412af255547987037a99fef8fafdd03ab1c68e34cd288160f9c6f611faa72072dae1abc70eaa47548cbe2b136606c936294350537af70

test:
  secret_key_base: f6f87115637a5c672fa20a8120e3416fef17c4c1a893ca43f85828be224f3960db119157a94a6367f707022961f844fb43f3cca8876b23b15e6c6bacc5d65483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
